import type { Metadata } from "next";
import { Bodoni_Moda,  Montserrat,Hahmlet} from "next/font/google";
import "./globals.scss";

const bodoni = Bodoni_Moda({ subsets: ["latin"], variable:'--fontHead' });
const hahmlet = Hahmlet({ subsets: ["latin"],variable:'--fontPara'},);
const monstserrat = Montserrat({ subsets: ["latin"],variable:'--fontAlt'},);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bodoni.className + ' ' + hahmlet.className + ' ' + monstserrat.className + ' '}>{children}</body>
    </html>
  );
}
